function [theHM,theH0,theHP]=convertFromGensysIn(g0,g1,pi)
%function [theHM,theH0,theHP]=convertFromGensysIn(g0,g1,pi)
gDim=size(g0,1);
piCol=size(pi,2);
theHM=sparse([...
-g1,zeros(gDim,piCol)
zeros(piCol,gDim+piCol)]);
theH0=sparse([...
g0,-pi;...
zeros(piCol,gDim+piCol)]);
theHP=sparse([...
zeros(gDim,gDim+piCol);...
zeros(piCol,gDim),eye(piCol)]);
