% 
% Status : main Dynare file 
% 
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ exedet_ exdet_ recur_ recurs_ 
global options_ endval_
global ys0_ recurs0_ ex0_ ct_
options_ = [];
M_.fname = 'q3a50';
% 
% Some global variables initialisation
% 
global_initialization;
diary off;
warning off;

delete q3a50.log;
warning on;
warning backtrace;
logname_ = 'q3a50.log';
diary 'q3a50.log';
erase_compiled_function('q3a50_static');
erase_compiled_function('q3a50_dynamic');
M_.exo_names = 'e';
M_.exo_names_tex = '';
M_.exo_names = strvcat(M_.exo_names,'e1');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e2');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e3');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e4');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e5');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e6');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e7');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e8');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e9');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e10');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e11');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e12');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e13');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e14');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e15');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e16');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e17');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e18');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e19');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e20');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e21');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e22');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e23');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e24');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e25');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e26');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e27');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e28');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e29');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e30');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e31');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e32');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e33');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e34');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e35');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e36');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e37');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e38');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e39');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e40');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e41');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e42');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e43');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e44');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e45');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e46');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e47');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e48');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e49');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'e50');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.endo_names = 'c';
M_.endo_names_tex = '';
M_.endo_names = strvcat(M_.endo_names,'a1');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k1');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a2');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k2');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a3');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k3');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a4');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k4');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a5');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k5');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a6');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k6');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a7');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k7');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a8');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k8');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a9');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k9');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a10');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k10');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a11');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k11');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a12');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k12');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a13');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k13');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a14');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k14');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a15');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k15');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a16');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k16');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a17');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k17');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a18');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k18');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a19');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k19');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a20');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k20');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a21');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k21');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a22');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k22');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a23');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k23');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a24');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k24');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a25');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k25');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a26');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k26');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a27');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k27');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a28');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k28');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a29');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k29');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a30');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k30');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a31');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k31');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a32');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k32');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a33');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k33');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a34');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k34');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a35');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k35');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a36');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k36');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a37');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k37');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a38');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k38');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a39');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k39');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a40');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k40');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a41');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k41');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a42');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k42');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a43');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k43');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a44');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k44');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a45');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k45');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a46');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k46');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a47');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k47');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a48');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k48');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a49');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k49');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'a50');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'k50');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.param_names = 'beta';
M_.param_names_tex = '';
M_.param_names = strvcat(M_.param_names,'gamma');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'phi');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'delta');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'alpha');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'rho');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'zeta');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'sigma');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'N');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.exo_det_nbr = 0;
M_.exo_nbr = 51;
M_.Sigma_e = zeros(51, 51);
M_.endo_nbr = 101;
M_.recur_nbr = 0;
M_.param_nbr = 9;
M_.lead_lag_incidence = [
	 0 101 202;
	 1 102 203;
	 2 103 0;
	 3 104 204;
	 4 105 0;
	 5 106 205;
	 6 107 0;
	 7 108 206;
	 8 109 0;
	 9 110 207;
	 10 111 0;
	 11 112 208;
	 12 113 0;
	 13 114 209;
	 14 115 0;
	 15 116 210;
	 16 117 0;
	 17 118 211;
	 18 119 0;
	 19 120 212;
	 20 121 0;
	 21 122 213;
	 22 123 0;
	 23 124 214;
	 24 125 0;
	 25 126 215;
	 26 127 0;
	 27 128 216;
	 28 129 0;
	 29 130 217;
	 30 131 0;
	 31 132 218;
	 32 133 0;
	 33 134 219;
	 34 135 0;
	 35 136 220;
	 36 137 0;
	 37 138 221;
	 38 139 0;
	 39 140 222;
	 40 141 0;
	 41 142 223;
	 42 143 0;
	 43 144 224;
	 44 145 0;
	 45 146 225;
	 46 147 0;
	 47 148 226;
	 48 149 0;
	 49 150 227;
	 50 151 0;
	 51 152 228;
	 52 153 0;
	 53 154 229;
	 54 155 0;
	 55 156 230;
	 56 157 0;
	 57 158 231;
	 58 159 0;
	 59 160 232;
	 60 161 0;
	 61 162 233;
	 62 163 0;
	 63 164 234;
	 64 165 0;
	 65 166 235;
	 66 167 0;
	 67 168 236;
	 68 169 0;
	 69 170 237;
	 70 171 0;
	 71 172 238;
	 72 173 0;
	 73 174 239;
	 74 175 0;
	 75 176 240;
	 76 177 0;
	 77 178 241;
	 78 179 0;
	 79 180 242;
	 80 181 0;
	 81 182 243;
	 82 183 0;
	 83 184 244;
	 84 185 0;
	 85 186 245;
	 86 187 0;
	 87 188 246;
	 88 189 0;
	 89 190 247;
	 90 191 0;
	 91 192 248;
	 92 193 0;
	 93 194 249;
	 94 195 0;
	 95 196 250;
	 96 197 0;
	 97 198 251;
	 98 199 0;
	 99 200 252;
	 100 201 0;]';
M_.exo_names_orig_ord = [1:51];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(101, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(51, 1);
M_.params = zeros(9, 1);
options_.periods = 5000;
options_.simul = 1;
M_.params( 5 ) = 0.36;
alpha = M_.params( 5 );
M_.params( 4 ) = 0.1;
delta = M_.params( 4 );
M_.params( 3 ) = 2;
phi = M_.params( 3 );
M_.params( 2 ) = 1;
gamma = M_.params( 2 );
M_.params( 1 ) = 0.99;
beta = M_.params( 1 );
M_.params( 6 ) = 0.95;
rho = M_.params( 6 );
M_.params( 7 ) = 2;
zeta = M_.params( 7 );
M_.params( 8 ) = 2;
sigma = M_.params( 8 );
M_.params( 9 ) = 50;
N = M_.params( 9 );
% 
% INITVAL instructions 
% 
options_.initval_file = 0;
endval_=0;
oo_.steady_state( 1 ) = 1;
oo_.exo_steady_state( 1 ) = 0;
oo_.steady_state( 2 ) = 1;
oo_.exo_steady_state( 2 ) = 0;
oo_.steady_state( 3 ) = 10;
oo_.steady_state( 4 ) = 1;
oo_.exo_steady_state( 3 ) = 0;
oo_.steady_state( 5 ) = 10;
oo_.steady_state( 6 ) = 1;
oo_.exo_steady_state( 4 ) = 0;
oo_.steady_state( 7 ) = 10;
oo_.steady_state( 8 ) = 1;
oo_.exo_steady_state( 5 ) = 0;
oo_.steady_state( 9 ) = 10;
oo_.steady_state( 10 ) = 1;
oo_.exo_steady_state( 6 ) = 0;
oo_.steady_state( 11 ) = 10;
oo_.steady_state( 12 ) = 1;
oo_.exo_steady_state( 7 ) = 0;
oo_.steady_state( 13 ) = 10;
oo_.steady_state( 14 ) = 1;
oo_.exo_steady_state( 8 ) = 0;
oo_.steady_state( 15 ) = 10;
oo_.steady_state( 16 ) = 1;
oo_.exo_steady_state( 9 ) = 0;
oo_.steady_state( 17 ) = 10;
oo_.steady_state( 18 ) = 1;
oo_.exo_steady_state( 10 ) = 0;
oo_.steady_state( 19 ) = 10;
oo_.steady_state( 20 ) = 1;
oo_.exo_steady_state( 11 ) = 0;
oo_.steady_state( 21 ) = 10;
oo_.steady_state( 22 ) = 1;
oo_.exo_steady_state( 12 ) = 0;
oo_.steady_state( 23 ) = 10;
oo_.steady_state( 24 ) = 1;
oo_.exo_steady_state( 13 ) = 0;
oo_.steady_state( 25 ) = 10;
oo_.steady_state( 26 ) = 1;
oo_.exo_steady_state( 14 ) = 0;
oo_.steady_state( 27 ) = 10;
oo_.steady_state( 28 ) = 1;
oo_.exo_steady_state( 15 ) = 0;
oo_.steady_state( 29 ) = 10;
oo_.steady_state( 30 ) = 1;
oo_.exo_steady_state( 16 ) = 0;
oo_.steady_state( 31 ) = 10;
oo_.steady_state( 32 ) = 1;
oo_.exo_steady_state( 17 ) = 0;
oo_.steady_state( 33 ) = 10;
oo_.steady_state( 34 ) = 1;
oo_.exo_steady_state( 18 ) = 0;
oo_.steady_state( 35 ) = 10;
oo_.steady_state( 36 ) = 1;
oo_.exo_steady_state( 19 ) = 0;
oo_.steady_state( 37 ) = 10;
oo_.steady_state( 38 ) = 1;
oo_.exo_steady_state( 20 ) = 0;
oo_.steady_state( 39 ) = 10;
oo_.steady_state( 40 ) = 1;
oo_.exo_steady_state( 21 ) = 0;
oo_.steady_state( 41 ) = 10;
oo_.steady_state( 42 ) = 1;
oo_.exo_steady_state( 22 ) = 0;
oo_.steady_state( 43 ) = 10;
oo_.steady_state( 44 ) = 1;
oo_.exo_steady_state( 23 ) = 0;
oo_.steady_state( 45 ) = 10;
oo_.steady_state( 46 ) = 1;
oo_.exo_steady_state( 24 ) = 0;
oo_.steady_state( 47 ) = 10;
oo_.steady_state( 48 ) = 1;
oo_.exo_steady_state( 25 ) = 0;
oo_.steady_state( 49 ) = 10;
oo_.steady_state( 50 ) = 1;
oo_.exo_steady_state( 26 ) = 0;
oo_.steady_state( 51 ) = 10;
oo_.steady_state( 52 ) = 1;
oo_.exo_steady_state( 27 ) = 0;
oo_.steady_state( 53 ) = 10;
oo_.steady_state( 54 ) = 1;
oo_.exo_steady_state( 28 ) = 0;
oo_.steady_state( 55 ) = 10;
oo_.steady_state( 56 ) = 1;
oo_.exo_steady_state( 29 ) = 0;
oo_.steady_state( 57 ) = 10;
oo_.steady_state( 58 ) = 1;
oo_.exo_steady_state( 30 ) = 0;
oo_.steady_state( 59 ) = 10;
oo_.steady_state( 60 ) = 1;
oo_.exo_steady_state( 31 ) = 0;
oo_.steady_state( 61 ) = 10;
oo_.steady_state( 62 ) = 1;
oo_.exo_steady_state( 32 ) = 0;
oo_.steady_state( 63 ) = 10;
oo_.steady_state( 64 ) = 1;
oo_.exo_steady_state( 33 ) = 0;
oo_.steady_state( 65 ) = 10;
oo_.steady_state( 66 ) = 1;
oo_.exo_steady_state( 34 ) = 0;
oo_.steady_state( 67 ) = 10;
oo_.steady_state( 68 ) = 1;
oo_.exo_steady_state( 35 ) = 0;
oo_.steady_state( 69 ) = 10;
oo_.steady_state( 70 ) = 1;
oo_.exo_steady_state( 36 ) = 0;
oo_.steady_state( 71 ) = 10;
oo_.steady_state( 72 ) = 1;
oo_.exo_steady_state( 37 ) = 0;
oo_.steady_state( 73 ) = 10;
oo_.steady_state( 74 ) = 1;
oo_.exo_steady_state( 38 ) = 0;
oo_.steady_state( 75 ) = 10;
oo_.steady_state( 76 ) = 1;
oo_.exo_steady_state( 39 ) = 0;
oo_.steady_state( 77 ) = 10;
oo_.steady_state( 78 ) = 1;
oo_.exo_steady_state( 40 ) = 0;
oo_.steady_state( 79 ) = 10;
oo_.steady_state( 80 ) = 1;
oo_.exo_steady_state( 41 ) = 0;
oo_.steady_state( 81 ) = 10;
oo_.steady_state( 82 ) = 1;
oo_.exo_steady_state( 42 ) = 0;
oo_.steady_state( 83 ) = 10;
oo_.steady_state( 84 ) = 1;
oo_.exo_steady_state( 43 ) = 0;
oo_.steady_state( 85 ) = 10;
oo_.steady_state( 86 ) = 1;
oo_.exo_steady_state( 44 ) = 0;
oo_.steady_state( 87 ) = 10;
oo_.steady_state( 88 ) = 1;
oo_.exo_steady_state( 45 ) = 0;
oo_.steady_state( 89 ) = 10;
oo_.steady_state( 90 ) = 1;
oo_.exo_steady_state( 46 ) = 0;
oo_.steady_state( 91 ) = 10;
oo_.steady_state( 92 ) = 1;
oo_.exo_steady_state( 47 ) = 0;
oo_.steady_state( 93 ) = 10;
oo_.steady_state( 94 ) = 1;
oo_.exo_steady_state( 48 ) = 0;
oo_.steady_state( 95 ) = 10;
oo_.steady_state( 96 ) = 1;
oo_.exo_steady_state( 49 ) = 0;
oo_.steady_state( 97 ) = 10;
oo_.steady_state( 98 ) = 1;
oo_.exo_steady_state( 50 ) = 0;
oo_.steady_state( 99 ) = 10;
oo_.steady_state( 100 ) = 1;
oo_.exo_steady_state( 51 ) = 0;
oo_.steady_state( 101 ) = 10;
oo_.y_simul=[oo_.steady_state*ones(1,M_.maximum_lag)];
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
save('q3a50_results', 'oo_');
diary off

disp(['Total computing time : ' sec2hms(round(toc)) ]);
