% 
% Status : main Dynare file 
% 
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ exedet_ exdet_ recur_ recurs_ 
global options_ endval_
global ys0_ recurs0_ ex0_ ct_
options_ = [];
M_.fname = 'sw_euro';
% 
% Some global variables initialisation
% 
global_initialization;
diary off;
warning off;

delete sw_euro.log;
warning on;
warning backtrace;
logname_ = 'sw_euro.log';
diary 'sw_euro.log';
erase_compiled_function('sw_euro_static');
erase_compiled_function('sw_euro_dynamic');
M_.exo_names = 'E_A';
M_.exo_names_tex = '';
M_.exo_names = strvcat(M_.exo_names,'E_B');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'E_G');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'E_L');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'E_I');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'ETA_R');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'E_PIE_BAR');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'ETA_Q');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'ETA_P');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'ETA_W');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.endo_names = 'MC';
M_.endo_names_tex = '';
M_.endo_names = strvcat(M_.endo_names,'EH');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'EF');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'R_KF');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'QF');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'CF');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'IF');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'YF');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'LF');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'PIEF');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'WF');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'RF');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'R_KH');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'QH');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'CH');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'IH');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'YH');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'LH');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'PIEH');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'WH');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'RH');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'EE_A');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'PIE_BAR');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'EE_B');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'EE_G');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'EE_L');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'EE_I');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'KF');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'KH');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'ONE');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.param_names = 'xi_e';
M_.param_names_tex = '';
M_.param_names = strvcat(M_.param_names,'lambda_w');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'alpha');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'czcap');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'beta');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'phi_i');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'tau');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'sig_c');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'hab');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'ccs');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'cinvs');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'phi_y');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'gamma_w');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'xi_w');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'gamma_p');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'xi_p');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'sig_l');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'r_dpi');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'r_pie');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'r_dy');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'r_y');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'rho');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'rho_a');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'rho_pb');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'rho_b');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'rho_g');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'rho_l');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'rho_i');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.exo_det_nbr = 0;
M_.exo_nbr = 10;
M_.Sigma_e = zeros(10, 10);
M_.endo_nbr = 30;
M_.recur_nbr = 0;
M_.param_nbr = 28;
M_.lead_lag_incidence = [
	 0 21 0;
	 1 22 51;
	 2 23 52;
	 0 24 53;
	 0 25 54;
	 3 26 55;
	 4 27 56;
	 5 28 0;
	 0 29 0;
	 0 30 57;
	 0 31 0;
	 0 32 0;
	 0 33 58;
	 0 34 59;
	 6 35 60;
	 7 36 61;
	 8 37 0;
	 0 38 0;
	 9 39 62;
	 10 40 63;
	 11 41 0;
	 12 42 0;
	 13 43 0;
	 14 44 0;
	 15 45 0;
	 16 46 0;
	 17 47 0;
	 18 48 0;
	 19 49 0;
	 20 50 0;]';
M_.exo_names_orig_ord = [1:10];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(30, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(10, 1);
M_.params = zeros(28, 1);
M_.params( 3 ) = .30;
alpha = M_.params( 3 );
M_.params( 5 ) = 0.99;
beta = M_.params( 5 );
M_.params( 7 ) = 0.025;
tau = M_.params( 7 );
M_.params( 10 ) = 0.6;
ccs = M_.params( 10 );
M_.params( 11 ) = .22;
cinvs = M_.params( 11 );
M_.params( 2 ) = 0.5;
lambda_w = M_.params( 2 );
M_.params( 6 ) = 6.771;
phi_i = M_.params( 6 );
M_.params( 8 ) = 1.353;
sig_c = M_.params( 8 );
M_.params( 9 ) = 0.573;
hab = M_.params( 9 );
M_.params( 14 ) = 0.737;
xi_w = M_.params( 14 );
M_.params( 17 ) = 2.400;
sig_l = M_.params( 17 );
M_.params( 16 ) = 0.908;
xi_p = M_.params( 16 );
M_.params( 1 ) = 0.599;
xi_e = M_.params( 1 );
M_.params( 13 ) = 0.763;
gamma_w = M_.params( 13 );
M_.params( 15 ) = 0.469;
gamma_p = M_.params( 15 );
M_.params( 4 ) = 0.169;
czcap = M_.params( 4 );
M_.params( 12 ) = 1.408;
phi_y = M_.params( 12 );
M_.params( 19 ) = 1.684;
r_pie = M_.params( 19 );
M_.params( 18 ) = 0.14;
r_dpi = M_.params( 18 );
M_.params( 22 ) = 0.961;
rho = M_.params( 22 );
M_.params( 21 ) = 0.099;
r_y = M_.params( 21 );
M_.params( 20 ) = 0.159;
r_dy = M_.params( 20 );
M_.params( 23 ) = 0.823;
rho_a = M_.params( 23 );
M_.params( 25 ) = 0.855;
rho_b = M_.params( 25 );
M_.params( 26 ) = 0.949;
rho_g = M_.params( 26 );
M_.params( 27 ) = 0.889;
rho_l = M_.params( 27 );
M_.params( 28 ) = 0.927;
rho_i = M_.params( 28 );
M_.params( 24 ) = 0.924;
rho_pb = M_.params( 24 );
save('sw_euro_results', 'oo_');
diary off

disp(['Total computing time : ' sec2hms(round(toc)) ]);
